---
stages:
- name: Build Stage
  inputs:
  - url: https://git.ng.bluemix.net/roliv/swift-enterprise-demo-20170615164613060.git
    type: git
    branch: master
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: roliv@us.ibm.com
      space: dev
      application: swift-enterprise-demo-20170615164613060
    script: |-
      #!/bin/bash
      cf create-service alertnotification authorizedusers SwiftEnterpriseDemo-Alert
      cf create-service Auto-Scaling free SwiftEnterpriseDemo-Auto-Scaling

      cf push "${CF_APP}"
      # View logs
      # cf logs "${CF_APP}" --recent
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
