---
stages:
- name: Build Stage
  inputs:
  - url: https://github.com/IBM-Bluemix/swift-helloworld.git
    type: git
    branch: toolchain-tst
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: roliv@us.ibm.com
      space: dev
      application: mypipeline
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
